server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
spring:
  application:
    name: gate-way-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: departmentService
            uri: lb://DEPARTMENT-SERVICE
            predicates:
              - Path=/department/**
          - id: uiService
            uri: lb://UI-SERVICE
            predicates:
              - Path=/ui/**


